function [DataTable,DataCell] = Full_Data_To_Table(AVA,DS)
  startTic = tic;
  AVA.VPrintF('Converting full data into table...')
  
  VesselDataCell = {DS.vesCenter,...
                    DS.vesCtrDistance,...
                    DS.vesDiameter,...
                    DS.turtosity,...
                    DS.lengthCum,...
                    DS.lengthStraight,...
                    }; 
  
  SegmentDataCell = { DS.segCenter,...
                      DS.segCtrDistance,...
                      DS.segDiameters,...
                      DS.angles,...
                      DS.ctrAngle,...
                      };
                       
  DataCell = {DS.area,...
              DS.imageCenter,...
              DS.nBranches,...
              DS.nVessel,...
              DS.nSegments,...
              DS.branchDensity,...
              DS.vesselDensity,...
              DS.totalLength,...
              VesselDataCell,...
              SegmentDataCell,...
              };

  DataTable = cell2table(DataCell);

  DataTable.Properties.VariableNames = {...
    'area',...
    'imageCenter',...
    'nBranches',...
    'nVessel',...
    'nSegments',...
    'branchDensity',...
    'vesselDensity',...
    'totalLength',...
    'VesselData',...
    'SegmentData'};

  DataTable.Properties.VariableDescriptions = {,...
    'area',...
    'location of wound center',...
    'nBranches',...
    'nVessel',...
    'nSegments',...
    'branchDensity',...
    'vesselDensity',...
    'totalLength',...
    'vesCenter, vesCtrDistance, vesDiameter, turtosity, lengthCum, lengthStraight',...
    'segCenter, segCtrDistance, segDiameters, angles, ctrAngle',...
    };

  DataTable.Properties.VariableUnits{'area'} = 'Px^2';
  DataTable.Properties.VariableUnits{'branchDensity'} = 'branches/Px^2';
  DataTable.Properties.VariableUnits{'vesselDensity'} = 'vessels/Px^2';

  AVA.Done(startTic);
  
end