function [DataTable,DataCell] = Full_Data_To_Table(AVA,DS)
  startTic = tic;
  
  AVA.VPrintF('Converting full data into table...')
  
  VesselDataCell = {DS.vesCenter,...
                    DS.vesCtrDistance,...
                    DS.vesDiameter,...
                    DS.turtosity,...
                    DS.lengthCum,...
                    DS.lengthStraight,...
                    }; 
  
  SegmentDataCell = { DS.segCenter,...
                      DS.segCtrDistance,...
                      DS.segDiameters,...
                      DS.angles,...
                      DS.ctrAngle,...
                      };
            
  DataCell = {...
              DS.nBranches,...
              DS.nVessel,...
              DS.nSegments,...
              DS.branchDensity,...
              DS.vesselDensity,...
              DS.totalLength,...
              DS.lengthFraction,...
              DS.vesselGrowthDensity,...
              DS.branchGrowthDensity,...
              DS.lengthGrowthFraction,... 
              DS.meanDiameter,...
              DS.meanLength,...
              DS.meanTurtosity,...
              DS.meanCtrAngle,...
              DS.medianDiameter,...
              DS.medianLength,...
              DS.medianTurtosity,...
              DS.medianCtrAngle,...
              DS.area,...
              DS.growthArea,...
              DS.imageCenter,...
              VesselDataCell,...
              SegmentDataCell,...
              };

  DataTable = cell2table(DataCell);

  DataTable.Properties.VariableNames = {...
    'nBranches',...
    'nVessel',...
    'nSegments',...
    'branchDensity',...
    'vesselDensity',...
    'totalLength',...
    'lengthFraction',...
    'vesselGrowthDensity',...
    'branchGrowthDensity',...
    'lengthGrowthFraction',...
    'meanDiameter',...
    'meanLength',...
    'meanTurtosity',...
    'meanCtrAngle',...
    'medianDiameter',...
    'medianLength',...
    'medianTurtosity',...
    'medianCtrAngle',...
    'area',...
    'growthArea',...
    'imageCenter',...
    'VesselData',...
    'SegmentData'};

  DataTable.Properties.VariableDescriptions = {...
    'nBranches',...
    'nVessel',...
    'nSegments',...
    'branchDensity',...
    'vesselDensity',...
    'totalLength',...
    'total length / area',...
    'vesselGrowthDensity',...
    'branchGrowthDensity',...
    'lengthGrowthFraction',...
    'average diameter of all vessel segments',...
    'average length of all vessels',...
    'average turtosity of all vessels',...
    'average angular deviation of all vessel segments',...
    'median diameter of all vessel segments',...
    'median length of all vessels',...
    'median turtosity of all vessels',...
    'median angular deviation of all vessel segments',...
    'area',...
    'area where actual vessels are growing',...
    'location of wound center',...
    'vesCenter, vesCtrDistance, vesDiameter, turtosity, lengthCum, lengthStraight',...
    'segCenter, segCtrDistance, segDiameters, angles, ctrAngle',...
    };

  DataTable.Properties.VariableUnits{'area'} = 'Px^2';
  DataTable.Properties.VariableUnits{'branchDensity'} = 'branches/Px^2';
  DataTable.Properties.VariableUnits{'vesselDensity'} = 'vessels/Px^2';

  AVA.Done(startTic);
  
end